version: 2.1

orbs:
    aws-cli: circleci/aws-cli@3.1.3

commands:
  fetch-token:
    steps:
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::352302322568:role/circle-ci-assume-role'
          role-session-name: 'ci-session'
      - run:
          name: Fetch secret and set env var
          command: |
            RETRIEVED_SECRET=$(aws secretsmanager get-secret-value --secret-id production/npm_github_token_ci --query SecretString --output text)
            SECRET_VALUE=$(node -pe 'JSON.parse(process.argv[1]).NPM_GITHUB_TOKEN' $RETRIEVED_SECRET)
            echo 'export NPM_GITHUB_TOKEN="$SECRET_VALUE"' >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          command: |
            sudo rm -r ~/.aws

jobs:
  publish-package:
    docker:
      - image: 352302322568.dkr.ecr.us-east-1.amazonaws.com/mm-ecs/ci-node:12.13.0.0
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps: 
      - run:
          name: Publish to package repo
          command: NPM publish
  node-12:
    docker:
      - image: 352302322568.dkr.ecr.us-east-1.amazonaws.com/mm-ecs/ci-node:12.13.0.0
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - fetch-token
      - restore_cache:
          key: worker-state-full-12-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: aws sts get-caller-identity
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-12-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
workflows:
  build-all:
    jobs:
      - node-12:
          context:
              - temp-context
      - publish-package:
          context:
              - temp-context
          requires:
            - node-12
          filters:
            branches:
              only: master
