version: 2.1
executorType: docker

orbs:
    aws-cli: circleci/aws-cli@3.1.3

commands:
  fetch-token:
    steps:
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::352302322568:role/circle-ci-assume-role'
          role-session-name: 'ci-session'
      - run:
          command: aws sts get-caller-identity
      - run:
          name: Fetch secret and set env var
          command: |
            RETRIEVED_SECRET=$(aws secretsmanager get-secret-value --secret-id production/npm_github_token_ci --query SecretString --output text)
            SECRET_VALUE=$(node -pe 'JSON.parse(process.argv[1]).NPM_GITHUB_TOKEN' $RETRIEVED_SECRET)
            echo 'export NPM_GITHUB_TOKEN="$SECRET_VALUE"' >> "$BASH_ENV"
            echo $SECRET_VALUE
            source "$BASH_ENV"
            echo $NPM_GITHUB_TOKEN
      - run:
          command: echo ${NPM_GITHUB_TOKEN}

jobs:          
  node-8:
    docker:
      - image: 352302322568.dkr.ecr.us-west-2.amazonaws.com/mm-ecs/ci-node:8.9.4.0
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - restore_cache:
          key: worker-state-full-8-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: echo ${NPM_GITHUB_TOKEN}
      - run:
          command: rm -f ./.npmrc
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-8-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
  node-12:
    docker:
      - image: 352302322568.dkr.ecr.us-east-1.amazonaws.com/mm-ecs/ci-node:12.13.0.0
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - fetch-token
      - restore_cache:
          key: worker-state-full-12-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: echo $BASH_ENV
      - run:
          command: echo ${NPM_GITHUB_TOKEN}
      - run:
          command: rm -f ./.npmrc
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-12-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
workflows:
  build-all:
    jobs:
      - node-12:
      - node-8:
          requires: # Run serially, since global Dynamo resources are shared.
            - node-12
