version: 2
executorType: docker
jobs:
  node-8:
    docker:
      - image: 352302322568.dkr.ecr.us-west-2.amazonaws.com/mm-ecs/ci-node:8.9.4.0
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - restore_cache:
          key: worker-state-full-8-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-8-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
  node-10:
    docker:
      - image: 352302322568.dkr.ecr.us-east-1.amazonaws.com/mm-ecs/ci-node:10.15.3.1
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - restore_cache:
          key: worker-state-full-10-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-10-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
  node-12:
    docker:
      - image: 352302322568.dkr.ecr.us-east-1.amazonaws.com/mm-ecs/ci-node:12.13.0.0
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - restore_cache:
          key: worker-state-full-10-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-10-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
workflows:
  version: 2
  build-all: # Jobs run serially, since global Dynamo resources are shared.
    jobs:
      - node-8
      - node-10:
          requires:
            - node-8
      - node-12:
          requires:
            - node-10
