version: 2.1
orbs:
  npm-publish: machinemetrics/npm-publish@0.1.2

executorType: docker
jobs:
  node-20:
    docker:
      - image: 352302322568.dkr.ecr.us-west-2.amazonaws.com/mm-ecs/ci-node:20.3.1.0
      - image: 352302322568.dkr.ecr.us-west-2.amazonaws.com/mm-data-platform/redis:8da63f72fa4ab3a49ee9301947525baa67f6581d
      - image: 352302322568.dkr.ecr.us-west-2.amazonaws.com/mm-data-platform/redis-test:1702aafd8728cb3b8d0885a182d82bc37997fafd
    working_directory: ~/worker-state
    steps:
      - checkout
      - restore_cache:
          key: worker-state-full-20-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-20-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
      - when:
          condition:
            equal: [npm-master, <<pipeline.git.branch>>]
          steps:
            - npm-publish/publish:
                role-arn: arn:aws:iam::352302322568:role/circle-ci-npm-artifact
workflows:
  version: 2
  build-all:
    jobs:
      - node-20
