version: 2.1

orbs:
    aws-cli: circleci/aws-cli@3.1.3
    node-packages: machinemetrics/node-packages@0.0.1

jobs:
  node-12:
    docker:
      - image: 352302322568.dkr.ecr.us-east-1.amazonaws.com/mm-ecs/ci-node:12.13.0.0
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
      - image: redis:3.2.6
    working_directory: ~/worker-state
    steps:
      - checkout
      - node-packages/fetch-token:
          role-arn: arn:aws:iam::352302322568:role/circle-ci-worker-state
      - restore_cache:
          key: worker-state-full-12-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: worker-state-full-12-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/worker-state/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/worker-state/coverage
workflows:
  build-all:
    jobs:
      - node-12:
          context:
              - temp-context
      - node-packages/publish-package:
          context:
              - temp-context
          requires:
            - node-12
          filters:
            branches:
              only: master
